db:
  image: mysql:5.7
  ports:
    - "3306:3306"
  restart: always
  environment:
    MYSQL_DATABASE: restaurante
    MYSQL_USER: pedrohfs
    MYSQL_PASSWORD: root
    MYSQL_ROOT_PASSWORD: root
  volumes:
    - db-data:/var/lib/mysql




